language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye_assignment7-${TRAVIS_JOB_NUMBER}.zip build/libs/test-1.0.0.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye_assignment7-${TRAVIS_JOB_NUMBER}.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd


before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: $key_id
    secret_access_key:
      secure: $secure
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall-jing.yu.me
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIFZTTDPUGY3JXMRA
    bucket: code-deploy.csye6225-fall-jing.yu.me
    key: csye_assignment7-${TRAVIS_JOB_NUMBER}.zip
    bundle_type: zip
    application: csye6225
    deployment_group: csye6225
    region: us-east-1
    secret_access_key:
      secure: $secure
    wait-until-deployed: true
    on:
      all_branches: true

#notifications:
#  email:
#    recipients:
#      - wang.shirui@husky.neu.edu
#      - yan.hao@husky.neu.edu
#      - jing.yu@husky.neu.edu
#      - ma.wenhe@husky.neu.edu
