language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye_assignment7-${TRAVIS_JOB_NUMBER}.zip build/libs/test-1.0.0.war appspec.yml
  - ls -al
  - mv csye_assignment7-${TRAVIS_JOB_NUMBER}.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..
  - pwd

deploy:
  - provider: s3
    access_key_id: AKIAIKS3JQUCDYF5GB7A

    secret_access_key:
      secure: iMOVhER09HKVTXd9JzIWblsf2K3sFnjXSpQLGErsiv0qe6cCe1jHeozNi4Zfo5duPPRr5oJkLEvb42TXspBLbSeZjernVkNF8in4OJGxf9EuMV+RgPEFudRXija/xOpc0yT5LKn8fKeg0ogj07vlrNhj17V81cRoLaCOfAN2lCm4f9NmV++9hjwvy4sCrw8E+O2oXi+b0IEEReq69JrXtUoYQvZ2mUTpFUIW8IvGoK1xnI/oX0MHkoPqDEvN5CPdOHHp2TYiC2ynBy70k+z22ezo8VB1eReu2y3xSxO8Fz+mBCUGMjXaWCexbNZ3IYKuY0D/OvARz14W7U/COldraRn9/z2GU92TvaCiLI/jQ51g4fXgJmN+NhF9qC6tyU3ETG68RvCHgVbemZ0fIUMi1wuEQ3Si/Yf9z1cNJApnlom4+9E/B1eUkJBnNRc5zgppy8dJ3PGiESR8kW/1XLIdimbGiGN01LlOw3TzssvMRSLzee9Qy5NJdKzd1Fuyq09O2KZcWAii6kFqmbGGbcVkm8/h7SHQX2CotXgEzkB9rWREtqWWMQJXkW+DypqsDkQT3i6E3MHFOKkBoRDgrqjubyby8pAqweGIDrVIOXcpTvDdPnD+vI+Ft0V4IPKHamDW4C33nljykf4PE7sRB4EIBN+gbii6M7XG+QOZsDKKgqo=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-mawenhe.me
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIKS3JQUCDYF5GB7A
    secret_access_key:
      secure: iMOVhER09HKVTXd9JzIWblsf2K3sFnjXSpQLGErsiv0qe6cCe1jHeozNi4Zfo5duPPRr5oJkLEvb42TXspBLbSeZjernVkNF8in4OJGxf9EuMV+RgPEFudRXija/xOpc0yT5LKn8fKeg0ogj07vlrNhj17V81cRoLaCOfAN2lCm4f9NmV++9hjwvy4sCrw8E+O2oXi+b0IEEReq69JrXtUoYQvZ2mUTpFUIW8IvGoK1xnI/oX0MHkoPqDEvN5CPdOHHp2TYiC2ynBy70k+z22ezo8VB1eReu2y3xSxO8Fz+mBCUGMjXaWCexbNZ3IYKuY0D/OvARz14W7U/COldraRn9/z2GU92TvaCiLI/jQ51g4fXgJmN+NhF9qC6tyU3ETG68RvCHgVbemZ0fIUMi1wuEQ3Si/Yf9z1cNJApnlom4+9E/B1eUkJBnNRc5zgppy8dJ3PGiESR8kW/1XLIdimbGiGN01LlOw3TzssvMRSLzee9Qy5NJdKzd1Fuyq09O2KZcWAii6kFqmbGGbcVkm8/h7SHQX2CotXgEzkB9rWREtqWWMQJXkW+DypqsDkQT3i6E3MHFOKkBoRDgrqjubyby8pAqweGIDrVIOXcpTvDdPnD+vI+Ft0V4IPKHamDW4C33nljykf4PE7sRB4EIBN+gbii6M7XG+QOZsDKKgqo=
    bucket: code-deploy.csye6225-fall2017-mawenhe.me
    key: csye_assignment7-${TRAVIS_JOB_NUMBER}.zip
    bundle_type: zip
    application: codeDeploy
    deployment_group: codeDeploy
    region: us-east-1
    wait-until-deployed: true
    on:
      all_branches: true
    
notifications:
  email:
    recipients:
      - wang.shirui@husky.neu.edu
      - yan.hao@husky.neu.edu
      - jing.yu@husky.neu.edu
      - ma.wenhe@husky.neu.edu
      
