language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye_assignment7-${TRAVIS_JOB_NUMBER}.zip build/libs/test-1.0.0.war appspec.yml
  - ls -al
  - mv csye_assignment7-${TRAVIS_JOB_NUMBER}.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIHT54JJWV5TWZEDA
    secret_access_key:
      secure: dsNOt4HaU+oJE+g+V8FpOL0GTfp3VuPTCyT/gbcRjGIG2B1E/aZiyShuojf1VxmaFA3UGom8lmMaTo9oDgDI/n3wQ6YqZCOwQeitK5Y8eG0fSVNjg94J8xeXzO/0nUd6tMs+Vr8Pxc9zuryybHw7VS83q0/oUer8wj6HOtoI190Cl85aXR11PgxVAUaB12mht08hBNseAAb0NsLi2irmk8EwQJRhxg2DaV1mpIHgCIBnawT5DZK4KeI4XV95WLqbkblF7UaA02vER8f0afors3VQTnYp6ZELt4UaLbjoHSscWHvmN04H0+UdwpCO/bLR6gIOws34O9JrEq0Y725jaxceo/RLOA6g4oL8AO5KRjEPFUlJuvn3ICg85xwMHpY8uOnV2TK0sTnSA19rLASPQqk2nbFd5ykmtAN7M7vpQhgWBsRVjim3Rxu8dX+q1ltm+2QUN4qWEpL3pSZcO8q94ImY71oTtgWjlh2re9r6yk5MIBJef7icjqdvD/7l5PYfDM3ENssJbt5W2eBCTZpCYecHcG+n/pkKfaTmwdGSUiA+aFZUj5QcM3txDALtXlCLpDeeWNnIe67A1aHnRvmXqWhCeuXtgvQnbz/0CzDBYwxU2G1kZeMqhIzOZXpChiaafyNR2iWDEtB9QrOAjPsZpaCR/t6Qn/j7BoWy7X1x2Ck=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-mawenhe.me
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIHT54JJWV5TWZEDA
    bucket: code-deploy.csye6225-fall2017-mawenhe.me
    key: csye_assignment7-${TRAVIS_JOB_NUMBER}.zip
    bundle_type: zip
    application: csye_assignment7-${TRAVIS_JOB_NUMBER}
    deployment_group: csye_assignment7
    region: us-east-1
    secret_access_key:
      secure: dsNOt4HaU+oJE+g+V8FpOL0GTfp3VuPTCyT/gbcRjGIG2B1E/aZiyShuojf1VxmaFA3UGom8lmMaTo9oDgDI/n3wQ6YqZCOwQeitK5Y8eG0fSVNjg94J8xeXzO/0nUd6tMs+Vr8Pxc9zuryybHw7VS83q0/oUer8wj6HOtoI190Cl85aXR11PgxVAUaB12mht08hBNseAAb0NsLi2irmk8EwQJRhxg2DaV1mpIHgCIBnawT5DZK4KeI4XV95WLqbkblF7UaA02vER8f0afors3VQTnYp6ZELt4UaLbjoHSscWHvmN04H0+UdwpCO/bLR6gIOws34O9JrEq0Y725jaxceo/RLOA6g4oL8AO5KRjEPFUlJuvn3ICg85xwMHpY8uOnV2TK0sTnSA19rLASPQqk2nbFd5ykmtAN7M7vpQhgWBsRVjim3Rxu8dX+q1ltm+2QUN4qWEpL3pSZcO8q94ImY71oTtgWjlh2re9r6yk5MIBJef7icjqdvD/7l5PYfDM3ENssJbt5W2eBCTZpCYecHcG+n/pkKfaTmwdGSUiA+aFZUj5QcM3txDALtXlCLpDeeWNnIe67A1aHnRvmXqWhCeuXtgvQnbz/0CzDBYwxU2G1kZeMqhIzOZXpChiaafyNR2iWDEtB9QrOAjPsZpaCR/t6Qn/j7BoWy7X1x2Ck=
    wait-until-deployed: true
    on:
      all_branches: true
    

notifications:
  email:
    recipients:
      - wang.shirui@husky.neu.edu
      - yan.hao@husky.neu.edu
      - jing.yu@husky.neu.edu
      - ma.wenhe@husky.neu.edu
      
