language: java
jdk:
- oraclejdk8
sudo: false
install: true
script:
- "./gradlew war"
- "./gradlew build"
notifications:
  email:
    recipients:
    - wang.shirui@husky.neu.edu
    - yan.hao@husky.neu.edu
    - jing.yu@husky.neu.edu
    - ma.wenhe@husky.neu.edu
