language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye_assignment7-TRAVIS_JOB_NUMBER.zip build/libs/test-1.0.0.war appspec.yml
  - ls -al
  - mv csye_assignment7-TRAVIS_JOB_NUMBER.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIFPBBWZL6NJXH63A
    secret_access_key:
      secure: MD88M0Ixlecza1Zd+ApIfakykPqX4sp3et7VeqLn1nExLUhRskbWLV2cmUw8GGBSfqQv+y0PkvEBTkDTC1TY+KwdLiqkhTxrulnUVVqXtE6SyCzUjT49ssXDGbVrZbe6f9Io1WdfAEP/OEZ5mdHtXlX6837UKc+mFbE52FylDtVa5CFD4/IYvi2gXNVKpzMSB29VRmKGvF+E64Kc0JzlTDm6VkFvIJjG2lAtEiaG9hJUjSyMete7sP6i1wnGVMQ7dNtPM2cl93n5rG1bVfohVhOecv05EPheMfAnCs3gPZOAzGuAywJd7hQ4pcnVXo76ubuCgCtrH1mmJN52w55BMBQiCArvto9kZvIFDpNU7R6ChgoifXOPamKF9Gm1C8fpgkkZS/2wTjnkRdcmN5XFOWnmDI/chRFv9xOEBqgh+C1jfqisoGgYFPrDu87ywbMFyugkEQZ95sl3VV8LdAfRvrlvnTFPdhNu5JbJXcTj7uZr3tRkNU+U5L1KiGeTSRBxriSPzzp79MqvEuops1FeaiFXkKASr9dwGPqzkkqM7gRk4HIP68sGatBn2mbN6EkoqGh7zVLAkoZDQ+Jml28Y2l9FZlj/+YL2az2z0MEPWrjExi3KAXC9smNKx2ZugqLp+NbVOIJ39pKVIIJoPIb9M85DK3cQfBc64BTln33aIoU=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-mawenhe.com
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIFPBBWZL6NJXH63A
    bucket: code-deploy.csye6225-fall2017-mawenhe.com
    key: SimpleJavaProject-${TRAVIS_JOB_NUMBER}.zip
    bundle_type: zip
    application: SimpleJavaProject
    deployment_group: SimpleJavaProject
    region: us-east-1
    secret_access_key:
      secure: MD88M0Ixlecza1Zd+ApIfakykPqX4sp3et7VeqLn1nExLUhRskbWLV2cmUw8GGBSfqQv+y0PkvEBTkDTC1TY+KwdLiqkhTxrulnUVVqXtE6SyCzUjT49ssXDGbVrZbe6f9Io1WdfAEP/OEZ5mdHtXlX6837UKc+mFbE52FylDtVa5CFD4/IYvi2gXNVKpzMSB29VRmKGvF+E64Kc0JzlTDm6VkFvIJjG2lAtEiaG9hJUjSyMete7sP6i1wnGVMQ7dNtPM2cl93n5rG1bVfohVhOecv05EPheMfAnCs3gPZOAzGuAywJd7hQ4pcnVXo76ubuCgCtrH1mmJN52w55BMBQiCArvto9kZvIFDpNU7R6ChgoifXOPamKF9Gm1C8fpgkkZS/2wTjnkRdcmN5XFOWnmDI/chRFv9xOEBqgh+C1jfqisoGgYFPrDu87ywbMFyugkEQZ95sl3VV8LdAfRvrlvnTFPdhNu5JbJXcTj7uZr3tRkNU+U5L1KiGeTSRBxriSPzzp79MqvEuops1FeaiFXkKASr9dwGPqzkkqM7gRk4HIP68sGatBn2mbN6EkoqGh7zVLAkoZDQ+Jml28Y2l9FZlj/+YL2az2z0MEPWrjExi3KAXC9smNKx2ZugqLp+NbVOIJ39pKVIIJoPIb9M85DK3cQfBc64BTln33aIoU=
    wait-until-deployed: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - wang.shirui@husky.neu.edu
      - yan.hao@husky.neu.edu
      - jing.yu@husky.neu.edu
      - ma.wenhe@husky.neu.edu
