language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye_assignment7-${TRAVIS_JOB_NUMBER}.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye_assignment7-${TRAVIS_JOB_NUMBER}.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd


before_deploy:
  - cd ..
  - pwd

deploy:
  - provider: s3
    access_key_id: AKIAIKS3JQUCDYF5GB7A
    secret_access_key:
      secure: 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
    local_dir: codedeploy
    bucket: csye6225bucket-cloudformation.com
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIKS3JQUCDYF5GB7A
    bucket: csye6225bucket-cloudformation.com
    key: csye_assignment7-${TRAVIS_JOB_NUMBER}.zip
    bundle_type: zip
    application: csye6225
    deployment_group: csye6225
    region: us-east-1
    secret_access_key:
      secure: aVQrNZhl6Y3HwAlj+EdBSOwGSBh9gn3gMS3hibSH
    wait-until-deployed: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - wang.shirui@husky.neu.edu
      - yan.hao@husky.neu.edu
      - jing.yu@husky.neu.edu
      - ma.wenhe@husky.neu.edu

