version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./createSetEnv.sh
    destination: /home/ubuntu
  - source: ./build/libs/csye6225app.war
    destination: /var/lib/tomcat8/webapps

hooks:
  AfterInstall:
    - location: ./createSetEnv.sh
    - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu

