<<<<<<< HEAD
version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./build/libs/test-1.0.0.war
    destination: /var/lib/tomcat7/webapps

hooks:
  AfterInstall:
   - location: ./restartTomcat.sh
     timeout: 180
<<<<<<< HEAD
     runas: ubuntu
=======
version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./build/libs/test-1.0.0.war
    destination: /var/lib/tomcat8/webapps

hooks:
  AfterInstall:
   - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu
>>>>>>> f75bfb39e9193c0e61ba96c0a1ecc7853a7e15cf
=======
     runas: ubuntu

     #comment
>>>>>>> 3110ad1f1496f4b8eef9a1800b51fd2ab2c35ece
